# Generated by Django 3.2.9 on 2021-11-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advisor_id', models.CharField(max_length=100)),
                ('Advisor_name', models.CharField(max_length=100)),
                ('Advisor_picture_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.CharField(max_length=100)),
                ('Booking_time', models.CharField(max_length=100)),
                ('Advisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experimental_API.advisor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experimental_API.user')),
            ],
        ),
    ]
